rouge: true
permalink: /:year/:month/:day/:title:output_ext
exclude: ['.git']
markdown: kramdown
name: "Veena Vignale"
description: "Website yay"
url: http://vvignale.github.io
baseurl: http://veenavignale.com
